# Generated by Django 3.1.7 on 2021-03-27 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, unique=True, verbose_name='Region')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('dateRegistered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=255, verbose_name='Ville')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('dateRegistered', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=255, unique=True, verbose_name='Agence')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='telephone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('dateRegistered', models.DateTimeField(default=django.utils.timezone.now)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.towns', verbose_name='Ville')),
            ],
        ),
    ]
